Aspects:
  # General
  - [vigorous, 13]
  - [overcharged, 15]
  - [mighty_storms]
  - [of_retribution, 29]
  - [ghostwalker, 25]
  - [of_the_umbral, 4]
  - [edgemasters, 20]
  - [of_disobedience, 1.0]
  - [juggernauts]
  - [earthguard, 24]
  - [of_shared_misery, 45]
  
  # Lightnig Storm 
  - [symbiotic, 4.5]
  - [of_retaliation, 28]
  - [of_natural_balance]
  - [of_the_stampede]
  - [shepherds, 9]
  - [lightning_dancers, 4000]
  - [of_inner_calm, 9]
  - [runeworkers, 1.8]

  # Shred
  - [of_the_blurred_beast, 40]
  - [stormclaws, 29]
  - [nighthowlers, 9]
  - [of_the_expectant, 19]
  - [of_the_tempest, 16]

  # Bear
  - [of_the_changelings_debt, 145]
  - [of_the_rampaging_werebeast, 5]
  - [balanced, 78]
  - [of_the_ursine_horror, 3000]
  - [bonebreaker, 90]
  - [of_the_trampled_earth, 78]

  # Nado
  - [stormchasers, 3]
  - [dire_wolfs, 24]

  # Boulder 
  - [of_metamorphic_stone, 118]
  - [of_the_aftershock, 11]
  - [rootfist, 19]
  - [seismic_shift, 0.5]

  # Rabies 
  - [of_the_alpha, 110]
  - [virulent, 0.5]

Affixes:
  - LSDruidTwoHand: 
      itemType: [two-handed axe, staff]
      minPower: 900
      affixPool:
        - [willpower]
        - [all-stats]
        - [core_skill_damage]
        - [damage_to_slowed_enemies]
        - [damage_to_poisoned_enemies]
        - [damage_to_close_enemies, 18]
        - [damage_to_distant_enemies, 12]
      minAffixCount: 3

  #- Helm:
   #   itemType: helm
   #   minPower: 800
   #   affixPool:
   #     - [basic_skill_attack_speed, 6]
      #  - [cooldown_reduction, 5]
     #   - [maximum_life, 580]
      #  - [lightning_resistance, 50]
   #     - [shadow_resistance, 50]
      #  - [fire_resistance, 50]
       # - [poison_resistance, 50]
      minAffixCount: 3

  - Armor:
      itemType: [chest armor, pants]
      minPower: 800
      affixPool:
        - [damage_reduction_while_fortified, 6]
        - [damage_reduction_from_close_enemies, 10]
        - [damage_reduction_from_poisoned_enemies, 6]
        - [damage_reduction_from_distant_enemies, 12]
        - [damage_reduction, 5]
        - [total_armour, 35]
        - [maximum_life, 700]
      minAffixCount: 3

  - Gloves:
      itemType: gloves
      minPower: 800
      affixPool:
        - [willpower, 35]
        - [lucky_hit_chance, 4]
        - [critical_strike_chance, 3]
        - [ranks_of_lightning_storm, 2]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 800
      affixPool:
        - [movement_speed, 15]
        - [willpower, 35]
        - [total_armor_while_in_werewolf_form, 15]
        - [all_stats, 25]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 800
      affixPool:
        - [damage_reduction_from_poisoned_enemies, 6]
        - [total_armor_while_in_werewolf_form, 15]
        - [total_armor, 9]
        - [movement_speed, 12]
        - [ranks_of_the_envenom_passive, 2]
      minAffixCount: 3

  - Ring:
      itemType: ring
      minPower: 800
      affixPool:
        - [critical_strike_chance, 4]
        - [lucky_hit_chance, 5]
        - [damage_to_close_enemies, 18]
        - [maximum_life, 680]
        - [damage_to_distant_enemies, 12]
      minAffixCount: 3
