# Whirlwind HotA Barbarian Endgame from d4builds.gg, no uber uniques variant - https://d4builds.gg/builds/8d5312e3-1a47-4e29-a496-f8f667ae4d7d/?var=1
Aspects:
  - [juggernauts]
  - [of_ancestral_force]
  - [relentless_berserkers]
  - [of_limitless_rage]
  - [earthstrikers]
  - [bold_chieftains]
  - [of_unrelenting_fury]
  - [edgemasters]
  - [of_elements]

Affixes:
  - Helm:
      itemType: [helm]
      minPower: 900
      affixPool:
        - [total_armor]
        - [cooldown_reduction]
        - [cold_resistance]
        - [fire_resistance]
      minAffixCount: 3

  - Armor:
      itemType: [chest armor, pants]
      minPower: 900
      affixPool:
        - [total_armor]
        - [damage_reduction]
        - [damage_reduction_while_fortified]
        - any_of:
            - [damage_reduction_from_bleeding_enemies]
            - [damage_reduction_while_injured]
            - [damage_reduction_from_close_enemies]
            - [maximum_life]
            - [resistance_to_all_elements]
      minAffixCount: 3

  - Gloves:
      itemType: gloves
      minPower: 900
      affixPool:
        - [ranks_of_hammer_of_the_ancients]
        - [strength]
        - [attack_speed]
        - [critical_strike_chance]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 900
      affixPool:
        - [movement_speed]
        - [poison_resistance]
        - [lightning_resistance]
        - [damage_reduction_while_injured]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 900
      affixPool:
        - [cooldown_reduction]
        - [fury_cost_reduction]
        - [ranks_of_the_counteroffensive_passive]
        - [total_armor]
      minAffixCount: 3

  - Ring:
      itemType: ring
      minPower: 900
      affixPool:
        - [critical_strike_chance]
        - [maximum_fury]
        - [damage_while_berserking]
        - [resource_generation]
      minAffixCount: 3

  - WeaponClose:
      itemType: [two-handed mace, two-handed axe]
      minPower: 900
      affixPool:
        - [damage_while_berserking]
        - [all_stats]
        - [overpower_damage]
        - [strength]
      minAffixCount: 3

  - WeaponClose2:
      itemType: [mace]
      minPower: 900
      affixPool:
        - [damage_while_berserking]
        - [all_stats]
        - [overpower_damage]
        - [strength]
      minAffixCount: 3
